### ISSUE TITLE
TypeError: ["build","deploy"].includes is not a function

### ISSUE THREAD

**Issue by fanqi** [liferay/lexicon-site#11]
```
➜  lexicon-site-master electric run
Running 'run'...
/Users/fanqi/Desktop/lexicon-site-master/electric.config.js:17
        if (['build', 'deploy'].includes(command)) {
                                ^

TypeError: ["build","deploy"].includes is not a function
    at Object.<anonymous> (/Users/fanqi/Desktop/lexicon-site-master/electric.config.js:17:26)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at applyConfigFile (/usr/local/lib/node_modules/electric-cli/node_modules/._electric@2.0.0-alpha.14@electric/lib/options.js:14:16)
    at normalizeOptions (/usr/local/lib/node_modules/electric-cli/node_modules/._electric@2.0.0-alpha.14@electric/lib/options.js:38:12)
    at Object.registerTasks (/usr/local/lib/node_modules/electric-cli/node_modules/._electric@2.0.0-alpha.14@electric/lib/index.js:9:12)

```

**Comment by natecavanaugh** [comment]
Heya @fanqi ,
thanks for the bug report. I'm gonna guess you're on node 4.x (or 5.x without the `--harmony` flag), but since 4.8.2 is a LTS supported version, I'll go ahead and fix this so there aren't any issues.

Thanks!
