### ISSUE TITLE
not compiling

### ISSUE THREAD

**Issue by victorvalle** [liferay/lexicon-site#33]
Hi!
My code is not compiling in the following branch: lexicon-upcoming.
I made a rebase and fixed all the issues I had but I can't run "el run" now. This is what I get:

[18:30:34] Starting 'metal:prep:pages'...
path.js:28
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:28:11)
    at Object.basename (path.js:1376:5)
    at Object.md.renderer.rules.image (/Users/victorvalle/Documents/Liferay/Lexicon Site upcoming/lexicon-site/markdown_plugins/retina_images.js:40:53)
    at Renderer.renderInline (/usr/local/lib/node_modules/electric-cli/node_modules/remarkable/lib/renderer.js:45:37)
    at Renderer.render (/usr/local/lib/node_modules/electric-cli/node_modules/remarkable/lib/renderer.js:69:22)
    at Remarkable.render (/usr/local/lib/node_modules/electric-cli/node_modules/remarkable/lib/index.js:152:24)
    at DestroyableTransform._transform (/usr/local/lib/node_modules/electric-cli/node_modules/electric/lib/pipelines/markdown.js:29:32)
    at DestroyableTransform.Transform._read (/usr/local/lib/node_modules/electric-cli/node_modules/readable-stream/lib/_stream_transform.js:182:10)
    at DestroyableTransform.Transform._write (/usr/local/lib/node_modules/electric-cli/node_modules/readable-stream/lib/_stream_transform.js:170:83)
    at doWrite (/usr/local/lib/node_modules/electric-cli/node_modules/readable-stream/lib/_stream_writable.js:406:64)

**Comment by Robert-Frampton** [comment]
Hey @victorvalle 

Have you updated your `lexicon-upcoming` branch? I tried building both the liferay lexicon-upcoming branch and your lexicon-upcoming branch and both build fine. If you have local changes can you push them up to your branch so I can test?

**Comment by victorvalle** [comment]
Sorry, maybe it is because it is in my repo: https://github.com/victorvalle/lexicon-site/tree/lexicon-upcoming

**Comment by victorvalle** [comment]
I solved it with Chema. Thanks! It was something I made wrong.
